### ISSUE TITLE
Amazon udacity-dl AMI not using GPU

### ISSUE THREAD

**Issue by EibrielInv** [udacity/dlnd-issue-reports#199]
The CUDA configuration is broken apparently due to an automatic update performed immediately after the instance is launched, here is my workaround: https://discussions.udacity.com/t/using-gpu-in-the-ec2-instance/231195/23?u=eibriel

**Comment by EibrielInv** [comment]
Copy pasting the workaround from the forum:

This will prevent the instance to access internet, but we will still be able to access the instance:

1. Go to VPC Management Console: https://console.aws.amazon.com/vpc/home
1. Follow the link `1 VPC`
1. Right click on the listed VPC, select Edit DNS Resolution and turn it off
1. Right click on the listed VPC, select Edit DNS Hostnames and turn it off

Launch a new instance:

1. Launch a new instance as usual (will be a bit slow because will be trying and failing to update things)
1. Edit the file `/etc/apt/apt.conf.d/10periodic` changing `APT::Periodic::Update-Package-Lists "1";` to `APT::Periodic::Update-Package-Lists "0";` (the only change is the number) to disable automatic updates

Re enable internet access:

1. Go to VPC Management Console: https://console.aws.amazon.com/vpc/home
1. Follow the link `1 VPC`
1. Right click on the listed VPC, select Edit DNS Resolution and turn it on
1. Right click on the listed VPC, select Edit DNS Hostnames and turn it on

Done, now Tensorflow will be able to use CUDA properly :grin:

**Comment by oritavital** [comment]
@Brok-Bucholtz  does it need to be updated on the project?

**Comment by EibrielInv** [comment]
Just discovered that this workaround is temporal, after some time the error appears:

```
E tensorflow/stream_executor/cuda/cuda_driver.cc:509] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: ip-172-31-79-171
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: ip-172-31-79-171
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 375.39.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:363] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.57  Mon Oct  3 20:37:01 PDT 2016
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 367.57.0
E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:303] kernel version 367.57.0 does not match DSO version 375.39.0 -- cannot find working devices in this configuration
```

**Comment by Brok-Bucholtz** [comment]
Ohh man, this doesn't look like it will be fun.  I'll check this out.

**Comment by EibrielInv** [comment]
On the forum someone posted: http://lodge.glasgownet.com/2017/03/21/aws-g2-gpu-vs-unattended-upgrade/

**Comment by Brok-Bucholtz** [comment]
Thanks for letting us know.  We've fixed the AMI!

Create a new instance with the "udacity-dl" AMI to fix the error.
